### PR TITLE
docs(api.md): small typo

### PR DESCRIPTION
**Pull request by nickvdyck**
In general I think the whole sentence needs a bit rephrasing. But first wanted to check with you guys.

### CODE REVIEW

**Comment by Hotell** [comment]
Hey thanks for helping out! I really appreciate that mister! What rephrasing are you suggesting? 

Anyway can you pls change the commit message to follow the commit guidelines which I forgot to publish? :D

https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines

**Comment by nickvdyck** [comment]
I see you added a contributing file, i'll adjust the commit message. When I created the PR I had a better way of phrasing this part. But at the moment I can't remember it (maybe I should have immediately  created the PR that way). 

Anyways at the moment I'm suggesting something like this:
- Implement this interface to execute custum logic after your component's data-bound properties,
bindings have been initialized and all controllers have been constructed. 

I just updated the commit message to conform contributing guidelines

**Comment by Hotell** [comment]
so if you agree with that, pls update it so we can merge it :)

**Comment by nickvdyck** [comment]
Yeah looks way better, i'll amend the changes when I'm at work.

**Comment by Hotell** [comment]
LGTM thank you!

**Pull request merged**
