### PR TITLE
Feat/enable prod mode

### PR DESCRIPTION
**Pull request by Hotell**

### CODE REVIEW

**Comment by JamesHenry** [comment]
What do you think about adding `$logProvider.debugEnabled(false)`?(https://docs.angularjs.org/api/ng/provider/$logProvider#!)

**Comment by Hotell** [comment]
yes I was  thinking to include that as well, but It might be to opinionated for consumer. wdyt?

**Comment by JamesHenry** [comment]
Hmm, yes perhaps. I personally won't be utilising this API anyway, purely for the personal preference of remaining explicit in my code around what I have enabled and disabled in prod, so feel free to ignore my suggestion :)

**Comment by Hotell** [comment]
Well you should consider using it, because if you are shipping code to production with enabled angular debug, you are doing something wrong ( you are loosing huge performance boost etc ). just sayin :)

**Comment by JamesHenry** [comment]
> personal preference of remaining explicit in my code around what I have enabled and disabled in prod

By that I meant that I am explicitly disabled debug mode in my own config block - not relying on a dependency (ng-metatdata) to do it for me.

**Comment by Hotell** [comment]
yeah, that's also option. thx for chat anyway! cheers

**Comment by JamesHenry** [comment]
Always a pleasure! It's just personal preference in this case, ng-metadata is doing everything else for me :D

**Pull request merged**
