### PR TITLE
Attr bindings via inputs

### PR DESCRIPTION
**Pull request by Hotell**

### CODE REVIEW

**Comment by JamesHenry** [comment]
Interesting, how come Attr has been removed? Is it no longer a thing in ng2?

**Comment by Hotell** [comment]
ng2 uses [`@Attributes`](https://angular.io/docs/ts/latest/api/core/Attribute-var.html) within `constructor`.
I may add it to ngMetadata but it's very low priority because you don't need it ( instead you should use abstractions via `@HostBindings` etc )

For public API, angular 2 uses just `@Input`. I've created the `@Attr` to mitigate the pain in Angular 1, because we need to distinct interpolation vs expression bindings. In ngMetadata 2.0 we will distinguish from within template as angular 2 does. So this is good time to refactor from `@Attr` to `@Input` so you public api looks like following with ngMetadata 1.x:

```html
<hero data="$ctrl.heroData" nickname="{{ $ctrl.nick }}"></component>
```
```typescript
@Component({
  selector:' hero',
  template: `Im no Hero!`
})
class HeroComponent{
  // one way
  @Input('<') data: {name:string,age:number};
 // interpolation 
  @Input('@') nickname: string;
}
```

then in ngMetadata 2.0 template will tell component what binding should be used ( the same as in Angular 2 )

```html
<hero [data]="$ctrl.heroData" nickname="{{ $ctrl.nick }}"></component>
```
```typescript
@Component({
  selector:' hero',
  template: `Im no Hero!`
})
class HeroComponent{
  @Input() data: {name:string,age:number};
  @Input() nickname: string;
}
```

so this is exactly how Angular 2 works, and is better for migration + more readable from declarative ( template ) perspective

**Comment by JamesHenry** [comment]
Awesome, thanks for taking the time to explain that. Makes perfect sense!

As an aside, are you looking for any contributions? You certainly seem to be making great progress yourself, but let me know if I can be of any help!

**Comment by Hotell** [comment]
thanks! will let you know, I can use some help for sure. I'll be on vacation for 2 weeks, so there will be no releases. Anyway 1.x is perfectly stable and has almost everything that Angular 2. 

So next one 2.0 in may ! :)

**Pull request merged**
