### PR TITLE
fix(manual_typings): Add boolean type to expensiveChecks (#72)

### LINKED ISSUE #72: Implicit `any` type in manual_typings/globals.d.ts
Hey @Hotell,

I have enabled the `noImplicitAny` flag for the TS compiler for my code base and I am down to one last error... in ng-metadata :)

The culprit is `expensiveChecks` in `manual_typings/globals.d.ts`:
```
interface IParseService{
    ( exp: string, interceptorFn?: Function, expensiveChecks? ): ng.ICompiledExpression
  }
```

Are you happy to accept a PR to annotate it explicitly with `: any`?

### PR DESCRIPTION
**Pull request by JamesHenry**
Fixes #72

### CODE REVIEW

**Comment by JamesHenry** [comment]
Hmm, not sure why that build failed...

**Comment by Hotell** [comment]
hmm travis has some problems with network during `npm install` or npm is down? :D strange

**Comment by JamesHenry** [comment]
`git merge --yolo`? :D

**Comment by Hotell** [comment]
:D LGTM

**Pull request merged**
